
CREATE TRIGGER music.INSC_INSERT
ON music.INSCRIPTIONS
AFTER INSERT AS
BEGIN
DECLARE @NEW_NOMBRE_PAIEMENTS INT ;
SELECT @NEW_NOMBRE_PAIEMENTS = nombre_de_paiements FROM inserted ;
IF @NEW_NOMBRE_PAIEMENTS < 1 or @NEW_NOMBRE_PAIEMENTS > 3
BEGIN
ROLLBACK TRANSACTION ;
THROW 99999,'Insertion interdite',1;
END;
END;
