
CREATE VIEW music.INTERVALLE_TRANCHES (ID_TRANCHE , QUOTIENTMIN , QUOTIENTMAX )
AS SELECT A.ID AS ID_TRANCHE, A.QUOTIENT_MIN AS QUOTIENTMIN, 
CASE WHEN B.QUOTIENT_MIN IS NULL THEN 10000
ELSE  B.QUOTIENT_MIN END  AS QUOTIENTMAX
FROM music.TRANCHES AS A
LEFT JOIN music.TRANCHES AS B
ON A.ID = B.ID-1
;

/*** SELECT id_tranche, quotientMin, quotientMax FROM INTERVALLE_TRANCHES  ***/