/***
Acteurs Sans films **/

SELECT A.NOM_ACTEUR, A.PRENOM_ACTEUR
FROM CINEMA.ACTEURS A
LEFT JOIN CINEMA.CASTING C
ON A.ID_ACTEUR = C.ID_ACTEUR
WHERE C.ID_ACTEUR IS NULL


/***
Films sans critique **/
SELECT F.TITRE_FILM
FROM CINEMA.FILMS F
LEFT JOIN CINEMA.EVALUATIONS E
ON F.ID_FILM = E.ID_FILM
WHERE E.ID_FILM IS NULL