SELECT C.NOM_CRITIQUE , F.TITRE_FILM
FROM CINEMA.CRITIQUE C
INNER JOIN CINEMA.EVALUATIONS E
ON C.ID_CRITIQUE = E.ID_CRITIQUE
INNER JOIN CINEMA.FILMS F
ON F.ID_FILM = E.ID_FILM
WHERE E.NOMBRE_ETOILES = 9.4
(SELECT MAX(NOMBRE_ETOILES) FROM CINEMA.EVALUATIONS  ) 
