DROP TABLE IF EXISTS SUPMASTER.CONTRAT ;

DROP TABLE IF EXISTS SUPMASTER.ORGANISATION ;

DROP TABLE IF EXISTS SUPMASTER.ACTIVITE ;

DROP TABLE IF EXISTS SUPMASTER.ETUDIANT ;

DROP TABLE IF EXISTS SUPMASTER.ETABLISSEMENT;

DROP TABLE IF EXISTS SUPMASTER.CURSUS ;

DROP TRIGGER IF EXISTS SUPMASTER.majNbContrats;

DROP SCHEMA IF EXISTS SUPMASTER;

