CREATE PROCEDURE ELEVE_FORME (@FILIERE VARCHAR(10) , @RESULTAT VARCHAR(50) OUTPUT,
@NBHEURECOURS INT OUTPUT) AS
BEGIN
DECLARE @NBEGAL INT ;

IF (@FILIERE IS NULL)
	SELECT @NBEGAL = COUNT(*) FROM PROCS.FORMATIONELEVES
	WHERE NB_HEURES_COURS_INFO = (SELECT MAX(NB_HEURES_COURS_INFO) FROM PROCS.FORMATIONELEVES) ;
ELSE
	SELECT @NBEGAL = COUNT(*) FROM PROCS.FORMATIONELEVES
	WHERE NB_HEURES_COURS_INFO = (SELECT MAX(NB_HEURES_COURS_INFO) FROM PROCS.FORMATIONELEVES
		WHERE CODE_FILIERE = @FILIERE) AND  CODE_FILIERE = @FILIERE;

IF (@NBEGAL = 0)
	SET @RESULTAT = 'Aucun élève n''est le plus expérimenté';
ELSE
	IF @NBEGAL > 1
	SET @RESULTAT = 'Plusieurs élèves ex aequo';
	ELSE
	BEGIN
		IF (@FILIERE IS NULL)
			SELECT @RESULTAT = CONCAT(NOM_ELEVE, CONCAT('-',CODE_FILIERE)),
				@NBHEURECOURS = NB_HEURES_COURS_INFO
			FROM PROCS.FORMATIONELEVES WHERE NB_HEURES_COURS_INFO = 
				(SELECT MAX(NB_HEURES_COURS_INFO) FROM PROCS.FORMATIONELEVES ) ;
		ELSE
			SELECT @RESULTAT = NOM_ELEVE,
				@NBHEURECOURS = NB_HEURES_COURS_INFO
			FROM PROCS.FORMATIONELEVES WHERE NB_HEURES_COURS_INFO = 
				(SELECT MAX(NB_HEURES_COURS_INFO) FROM PROCS.FORMATIONELEVES 
				WHERE CODE_FILIERE = @FILIERE) AND  CODE_FILIERE = @FILIERE;
 	END;
END;

