DECLARE @REQUETE VARCHAR(50) ,@NBH INT ;
EXEC ELEVE_FORME 'SLAM ENC' , @REQUETE OUTPUT , @NBH OUTPUT ;
PRINT @REQUETE ;
PRINT @NBH ;

DECLARE @REQUETE VARCHAR(50) ,@NBH INT ;
EXEC ELEVE_FORME NULL , @REQUETE OUTPUT , @NBH OUTPUT ;
PRINT @REQUETE ;
PRINT @NBH ;

DECLARE @REQUETE VARCHAR(50) ,@NBH INT ;
EXEC ELEVE_FORME 'SISR ENC' , @REQUETE OUTPUT , @NBH OUTPUT ;
PRINT @REQUETE ;
PRINT @NBH ;