ALTER TABLE ASDOMI.INTERVENTION
ADD CONSTRAINT FK_SALARIE 
FOREIGN KEY (matriculeSalarie) REFERENCES 
ASDOMI.SALARIE(MATRICULE);

ALTER TABLE ASDOMI.INTERVENTION
ADD CONSTRAINT FK_DOSSIER 
FOREIGN KEY (noDOSSIER) REFERENCES 
ASDOMI.DOSSIER(NUMERO);

ALTER TABLE ASDOMI.INTERVENTION
ADD CONSTRAINT FK_VEHICULE 
FOREIGN KEY (noVehicule) REFERENCES 
ASDOMI.VEHICULE(NUMERO);

GRANT SELECT TO PUBLIC ON ASDOMI.INTERVENTION ;

GRANT INSERT, UPDATE, DELETE TO RDeltour ON ASDOMI.INTERVENTION ;