SELECT MD.ID_MATCH 
FROM FOOTEDC.MATCH_DETAIL MD
WHERE MD.ID_EQUIPE IN (
SELECT PF.ID_PAYS 
FROM FOOTEDC.PAYS_FOOTBALL PF
WHERE PF.NOM_PAYS in ('Germany', 'Poland')) 
GROUP BY MD.ID_MATCH  
HAVING COUNT(MD.ID_MATCH )=2
;