SELECT J.NOMPRENOM_JOUEUR
FROM FOOTEDC.MATCH_DETAIL MD
INNER JOIN FOOTEDC.PAYS_FOOTBALL PF
ON MD.ID_EQUIPE = PF.ID_PAYS
AND PF.NOM_PAYS = 'Italy'
INNER JOIN (
SELECT *
FROM FOOTEDC.MATCH_DETAIL MD
INNER JOIN FOOTEDC.PAYS_FOOTBALL PF
ON MD.ID_EQUIPE = PF.ID_PAYS
AND PF.NOM_PAYS = 'Germany') SR
ON MD.ID_MATCH = SR.ID_MATCH
INNER JOIN FOOTEDC.JOUEURS J
ON J.ID_JOUEUR = MD.ID_JOUEUR_GARDIEN
INNER JOIN (SELECT DISTINCT ID_MATCH
FROM FOOTEDC.TIRS_AU_BUT_PENALTY
) TB
ON MD.ID_MATCH = TB.ID_MATCH