DROP TABLE  IF EXISTS FOOTEDC.ARBITRE;
DROP TABLE  IF EXISTS FOOTEDC.ENTRAINEUR;
DROP TABLE  IF EXISTS FOOTEDC.ENTRAINEUR_EQUIPE;
DROP TABLE  IF EXISTS FOOTEDC.EQUIPES;
DROP TABLE  IF EXISTS FOOTEDC.MATCH_SYNTHESE;
DROP TABLE  IF EXISTS FOOTEDC.MATCH_DETAIL;
DROP TABLE  IF EXISTS FOOTEDC.PAYS_FOOTBALL;
DROP TABLE  IF EXISTS FOOTEDC.STADE_FOOTBALL;
DROP TABLE  IF EXISTS FOOTEDC.STADE_VILLE;
 
DROP TABLE  IF EXISTS FOOTEDC.ARBITRE_ASSISTANT ;
DROP TABLE  IF EXISTS FOOTEDC.JOUEURS ;
DROP TABLE  IF EXISTS FOOTEDC.POSITION ;
DROP TABLE  IF EXISTS FOOTEDC.BUT_DETAIL ;
DROP TABLE  IF EXISTS FOOTEDC.TIRS_AU_BUT_PENALTY ;
DROP TABLE  IF EXISTS FOOTEDC.CARTONS ;
DROP TABLE  IF EXISTS FOOTEDC.REMPLACEMENTS ;
DROP TABLE  IF EXISTS FOOTEDC.CAPITAINES ;
DROP TABLE  IF EXISTS FOOTEDC.GARDIEN_MATCH_TIRSAUXBUTS ;
 
DROP SCHEMA IF EXISTS FOOTEDC;