CREATE SCHEMA FOOTEDC
GO
CREATE TABLE FOOTEDC.STADE_FOOTBALL
(
ID_STADE INT PRIMARY KEY,
NOM_STADE VARCHAR(60),
ID_VILLE INT ,
CAPACITE_STADE INT)
GO



CREATE TABLE FOOTEDC.STADE_VILLE
(
ID_VILLE INT PRIMARY KEY,
NOM_VILLE VARCHAR(60),
ID_PAYS INT )


CREATE TABLE FOOTEDC.PAYS_FOOTBALL
(
ID_PAYS INT PRIMARY KEY,
CODE_PAYS CHAR(3),
NOM_PAYS VARCHAR(60) )
GO

CREATE TABLE FOOTEDC.MATCH_SYNTHESE
( 
ID_MATCH INT PRIMARY KEY,
ETAPE_COMPETITION CHAR(1),
DATE_MATCH DATE,
RESULTAT VARCHAR(8),
DECISION CHAR(1),
SCORE CHAR(3),
ID_STADE INT,
ID_ARBITRE INT,
NB_SPECTATEURS INT ,
ID_JOUEUR_MATCH INT,
NBSEC_ARRET_JEU_1PERIODE INT,
NBSEC_ARRET_JEU_2PERIODE INT
);


CREATE TABLE FOOTEDC.ARBITRE
( 
ID_ARBITRE INT PRIMARY KEY,
PRENOM_NOM_ARBITRE VARCHAR(60),
ID_PAYS INT);

CREATE TABLE FOOTEDC.EQUIPES
( 
ID_EQUIPE INT PRIMARY KEY,
CODE_GROUPE CHAR(1),
NB_MATCHS_JOUES INT,
NB_MATCHS_GAGNES INT,
NB_MATCHS_NULS INT,
NB_MATCHS_PERDUS INT,
NB_BUTS_MARQUES INT,
NB_BUTS_ENCAISSES INT,
DIFFERENCE_BUTS INT,
NB_POINTS INT,
CLASSEMENT_GROUPE INT
);

CREATE TABLE FOOTEDC.ENTRAINEUR
(
ID_ENTRAINEUR INT PRIMARY KEY,
NOMPRENOM_ENTRAINEUR VARCHAR(60)
);

CREATE TABLE FOOTEDC.MATCH_DETAIL
( 
ID_MATCH INT,
ETAPE_COMPETITION CHAR(1),
ID_EQUIPE INT,
RESULTAT VARCHAR(8),
DECISION CHAR(1),
SCORE INT,
SCORE_PENALTY INT,
ID_ARBITRE_ASSISTANT INT,
ID_JOUEUR_GARDIEN INT
);



CREATE TABLE FOOTEDC.ENTRAINEUR_EQUIPE
( 
ID_EQUIPE INT,
ID_ENTRAINEUR INT
);





