
CREATE TABLE REALISATEUR
(		
   CLEF_REALISATEUR INT IDENTITY(1,1) PRIMARY KEY,
   NOM_REALISATEUR VARCHAR(60)
   
);

INSERT INTO REALISATEUR  VALUES ('EASTWOOD');
INSERT INTO REALISATEUR  VALUES ('LYNCH');
INSERT INTO REALISATEUR  VALUES ('COPPOLA');


CREATE TABLE FILM (
CLEF_FILM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CLEF_REALISATEUR INT FOREIGN KEY REFERENCES REALISATEUR (CLEF_REALISATEUR),
NUMERO_CATALOGUE VARCHAR(50) NOT NULL,
CATEGORIE VARCHAR(50) NOT NULL CHECK (CATEGORIE IN('Action', 'Famille', 'Drame', 'Comédie', 'Horreur', 'Fantastique', 'Science-fiction', 'Adulte')),
TITRE_FILM VARCHAR(50)
 );

INSERT INTO FILM  VALUES (3,'002032501','Action','Apocalypse Now');
INSERT INTO FILM  VALUES (3,'002032502','Action','The conversation');
INSERT INTO FILM  VALUES (2,'002032503','Fantastique','Twin Peaks saison 1');
INSERT INTO FILM  VALUES (2,'002064518','Fantastique','Twin Peaks saison 2');
INSERT INTO FILM  VALUES (2,'002066238','Fantastique','Twin Peaks saison 3');
INSERT INTO FILM  VALUES (1,'003866239','Drame','Million dollar baby');
INSERT INTO FILM  VALUES (1,'003866321','Action','Impitoyable');


CREATE TABLE ACTEUR 
(		
   CLEF_ACTEUR INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   NOM_ACTEUR VARCHAR(60)
);

INSERT INTO ACTEUR  VALUES ('EASTWOOD');
INSERT INTO ACTEUR  VALUES ('BRANDO');
INSERT INTO ACTEUR  VALUES ('DUVALL');
INSERT INTO ACTEUR  VALUES ('SHEEN');
INSERT INTO ACTEUR  VALUES ('HACKMAN');
INSERT INTO ACTEUR  VALUES ('LYNCH');
INSERT INTO ACTEUR  VALUES ('MACLACHLAN');
INSERT INTO ACTEUR  VALUES ('EASTWOOD');
INSERT INTO ACTEUR  VALUES ('SWANK');
INSERT INTO ACTEUR  VALUES ('FREEMAN');

CREATE TABLE FILM_ACTEUR 
(
	CLEF_FILM_ACTEUR INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CLEF_FILM INT NOT NULL FOREIGN KEY REFERENCES FILM (CLEF_FILM),
	CLEF_ACTEUR INT NOT NULL FOREIGN KEY REFERENCES ACTEUR (CLEF_ACTEUR),
	
);

INSERT INTO FILM_ACTEUR	VALUES (1,2);
INSERT INTO FILM_ACTEUR	VALUES (1,3);
INSERT INTO FILM_ACTEUR	VALUES (1,4);
INSERT INTO FILM_ACTEUR	VALUES (2,5);
INSERT INTO FILM_ACTEUR	VALUES (3,6);
INSERT INTO FILM_ACTEUR	VALUES (3,7);
INSERT INTO FILM_ACTEUR	VALUES (4,6);
INSERT INTO FILM_ACTEUR	VALUES (4,7);
INSERT INTO FILM_ACTEUR	VALUES (5,6);
INSERT INTO FILM_ACTEUR	VALUES (5,7);
INSERT INTO FILM_ACTEUR	VALUES (6,8);
INSERT INTO FILM_ACTEUR	VALUES (6,9);
INSERT INTO FILM_ACTEUR	VALUES (6,10);
INSERT INTO FILM_ACTEUR	VALUES (7,1);
INSERT INTO FILM_ACTEUR	VALUES (7,5);
INSERT INTO FILM_ACTEUR	VALUES (7,9);
