SELECT 
PF.NOM_PAYS AS NATIONALITE, 
A.PRENOM_NOM_ARBITRE
FROM FOOTEDC.PAYS_FOOTBALL PF
INNER JOIN FOOTEDC.ARBITRE A
ON PF.ID_PAYS = A.ID_PAYS
INNER JOIN FOOTEDC.MATCH_SYNTHESE M
ON M.ID_ARBITRE = A.ID_ARBITRE
WHERE M.DATE_MATCH = (SELECT MAX(DATE_MATCH) FROM FOOTEDC.MATCH_SYNTHESE)

/*** Possibilités avec ID_MATCH ou ETAPE_COMPETITION ***/