-- Partie 2 Question 1

SELECT 
COUNT(DISTINCT CP.CLEF_CANDIDAT) AS NB, P.NOM_POSTE

FROM POSTE P 
INNER JOIN CANDIDAT_POSTE CP
ON P.CLEF_POSTE = CP.CLEF_POSTE
GROUP BY P.NOM_POSTE

-- Partie 2 Question 2

SELECT
C.NOM_CANDIDAT, C.PRENOM_CANDIDAT
FROM CANDIDAT C 
INNER JOIN EST_DIPLOME ED
ON C.CLEF_CANDIDAT = ED.CLEF_CANDIDAT
INNER JOIN DIPLOME D
ON D.CLEF_DIPLOME = ED.CLEF_DIPLOME 
WHERE D.NOM_DIPLOME = 'DEA Economie Ressources Humaines'