SELECT SF.NOM_STADE,
SV.NOM_VILLE, COUNT(*) AS NB_MATCHS_JOUES
FROM FOOTEDC.STADE_VILLE SV
INNER JOIN FOOTEDC.STADE_FOOTBALL SF ON
SV.ID_VILLE = SF.ID_VILLE
INNER JOIN FOOTEDC.MATCH_SYNTHESE MS
ON MS.ID_STADE = SF.ID_STADE
GROUP BY 
SF.NOM_STADE,
SV.NOM_VILLE
