SELECT A.PRENOM_NOM_ARBITRE, P.NOM_PAYS 
FROM FOOT.MATCH_SYNTHESE M  
INNER JOIN FOOT.ARBITRE A ON M.ID_ARBITRE = A.ID_ARBITRE
INNER JOIN FOOT.PAYS_FOOTBALL P ON A.ID_PAYS = P.ID_PAYS
WHERE M.ID_MATCH=1;