CREATE TABLE TYPERETARD
( 
id INT NOT NULL PRIMARY KEY,
codeRetard CHAR(2),
nom VARCHAR(100)
) ;

INSERT INTO TYPERETARD VALUES(1,'AV','Avant vol Retard passager');
INSERT INTO TYPERETARD VALUES(2,'EV','En vol attaque terroriste');
INSERT INTO TYPERETARD VALUES(3,'AP','Après vol toboggan pas près');
INSERT INTO TYPERETARD VALUES(4,'AV','Occupation des pistes');



CREATE TABLE AEROPORT 
(OACI CHAR(4) NOT NULL PRIMARY KEY , 
AITA CHAR(3),
nom VARCHAR(100), 
latitude VARCHAR(10),
longitude VARCHAR(10)) ;

INSERT INTO AEROPORT VALUES('LFBD','BOD','Bordeaux-Mérignac','44-50N','000-42W') ;
INSERT INTO AEROPORT VALUES('LFLL','LYS','Lyon-Saint-Exupéry','45-44N','005-05E') ;
INSERT INTO AEROPORT VALUES('LFPG','CDG','Roissy-Charles-De-Gaulle','49N','002-54E') ;



CREATE TABLE AVION
(id CHAR(5) NOT NULL PRIMARY KEY,
MODELE VARCHAR(5) ,
numeroSerie VARCHAR(100),
codeInterne VARCHAR(100)
) ;

INSERT INTO AVION VALUES('FGFKA','A319','A319-1021','123456') ;
INSERT INTO AVION VALUES('FHBND','A320','A320-514','0357841') ;
INSERT INTO AVION VALUES('FGMPD','A319','A319-218','0548774') ;
INSERT INTO AVION VALUES('FGLZI','A343','A343-134','0124794') ;



CREATE TABLE MOUVEMENT
(
id INT NOT NULL PRIMARY KEY,
idAVion CHAR(5) NOT NULL FOREIGN KEY REFERENCES AVION(id) ,
numeroVol VARCHAR(10) ,
idAeroportDepart CHAR(4) FOREIGN KEY REFERENCES AEROPORT(OACI),
distance REAL,
nbPassagers INT,
estIntracom BIT,
dateHeureDepart DATETIME,
idAeroportArrivee CHAR(4) FOREIGN KEY REFERENCES AEROPORT(OACI),
dateHeureArrivee DATETIME,
dureeVol INT
);

INSERT INTO MOUVEMENT VALUES(
1221,'FGFKA','7410','LFBD', 450, 230, 1, '2013-07-17T18:30:00', 'LFLL','2013-07-17T19:45:00' , 75);

CREATE TABLE RETARD 
(
id INT NOT NULL PRIMARY KEY,
raison VARCHAR(200),
duree INT,
idType INT FOREIGN KEY REFERENCES TYPERETARD(id), 
idMvt INT FOREIGN KEY REFERENCES MOUVEMENT(id))
;

insert into RETARD values (2, 'Intemperies', 1, 2, 1221);
insert into RETARD values (1, 'Panne', 1, 1, 1221);

GO

	CREATE VIEW volsRetardes
	AS
	SELECT idMvt, distance, nbPassagers, estIntracom , dateHeureDepart, 
SUM(duree) As retardTotal
	FROM RETARD INNER JOIN MOUVEMENT
	ON RETARD.idMvt=MOUVEMENT.id
	GROUP BY idMvt, distance, nbPassagers, estIntracom, dateHeureDepart
